# Generated by Django 4.1.3 on 2022-11-24 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, error_messages={'invalid_extension': '%(value)s'}, max_length=500, null=True, upload_to='images/book-covers', validators=[django.core.validators.validate_image_file_extension], verbose_name='cover image'),
        ),
    ]
