# Generated by Django 4.1.3 on 2022-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(db_index=True, default='hamidreza samsami', max_length=100),
            preserve_default=False,
        ),
    ]
