# Generated by Django 4.1.3 on 2022-12-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published']},
        ),
    ]
