# Generated by Django 4.1.3 on 2022-12-01 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
