# Generated by Django 4.1.3 on 2022-12-01 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_published_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
