# Generated by Django 4.1.3 on 2022-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
