version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: wookie_app
    command: gunicorn wookie.wsgi:application --workers=2 --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/images
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-bullseye
    container_name: wookie_postgres
    restart: always
    env_file:
      - ./.env.prod.db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/images
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: wookie_redis
    environment:
      - REDIS_PORT_NUMBER=7000
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=password123
    ports:
      - '7000:7000'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local  